language: python
python:
- 2.7
install:
  - pip install -q --use-mirrors coveralls
script: make test
notifications:
  irc:
    skip_join: true
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org##nkuttler
  email:
    on_success: never
    on_failure: change
